name: EBAC CI

on: 
  push:
    branches: [ ci ]

jobs:
  cypress-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14 # ou a versão desejada do Node.js

    - name: Install dependencies
      run: npm install

    - name: Run Cypress tests and generate Allure report
      run: |
        npx cypress run --env allure=true
      continue-on-error: true

    - name: Upload Allure report
      uses: actions/upload-artifact@v2
      with:
        name: allure-report
        path: ./allure-report

  deploy-gh-pages:
    needs: cypress-tests
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./allure-report # Caminho para o diretório do relatório Allure

  # test:
  #   runs-on: ubuntu-latest

  #   steps:
  #     - uses: actions/checkout@v2
  #     - uses: actions/setup-node@v3
  #       with:
  #         node-version: 18
          
  #     - name: Executa os testes
  #       uses: cypress-io/github-action@v6
  #       continue-on-error: true
  #       with:
  #         env: allure=true
          
  #     - name: Checkout gh-pages
  #       uses: actions/checkout@v3
  #       if: always()
  #       continue-on-error: true
  #       with:
  #         ref: gh-pages # branch name
  #         path: gh-pages-dir # checkout path
  
  #     - name: Allure Report Action
  #       uses: mgrybyk/allure-report-branch-action@v1
  #       if: always()
  #       continue-on-error: true
  #       id: allure # used in comment to PR
  #       with:
  #         report_id: 'self-test'
  #         gh_pages: 'gh-pages-dir'
  #         report_dir: 'allure-results'
    
  #     - name: Git Commit and Push Action
  #       uses: mgrybyk/git-commit-pull-push-action@v1
  #       if: always()
  #       with:
  #         repository: gh-pages-dir
  #         branch: gh-pages
  #         pull_args: --rebase -X ours
  
  #     - name: Comment PR with Allure Report link
  #       if: ${{ always() && github.event_name == 'pull_request' && steps.allure.outputs.report_url }}
  #       continue-on-error: true
  #       uses: thollander/actions-comment-pull-request@v2
  #       with:
  #         message: |
  #           ${{ steps.allure.outputs.test_result_icon }} [Allure Report](${{ steps.allure.outputs.report_url }}) | [History](${{ steps.allure.outputs.report_history_url }})
  #         comment_tag: allure_report
  #         mode: recreate
      # - name: Get Allure history
      #   uses: actions/checkout@v2
      #   if: always()
      #   continue-on-error: true
      #   with:
      #     ref: gh-pages
      #     path: gh-pages
      # - name: Test marketplace action
      #   uses: simple-elf/allure-report-action@master
      #   if: always()
      #   id: allure-report
      #   with:
      #     allure_results: build/allure-results
      #     gh_pages: gh-pages
      #     allure_report: allure-report
      #     allure_history: allure-history
      # - name: Deploy report para Github Pages
      #   if: always()
      #   uses: peaceiris/actions-gh-pages@v2
      #   env:
      #     PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #     PUBLISH_BRANCH: gh-pages
      #     PUBLISH_DIR: allure-history
      # - name: Posta o link do report
      #   if: always()
      #   uses: Sibz/github-status-action@v1
      #   with: 
      #       authToken: ${{secrets.GITHUB_TOKEN}}
      #       context: 'Test report'
      #       state: 'success'
      #       sha: ${{ github.event.pull_request.head.sha }}
      #       target_url: simple-elf.github.io/github-allure-history/${{ github.run_number }}
