name: EBAC CI
on:
  push:
    branches: [ci]
jobs:
  cypress-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Instala o Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18.17.1" # ou a versão desejada do Node.js

      - name: Checkout no codigo
        uses: actions/checkout@v2

      - name: Instala as dependencias
        run: npm install

      - name: Roda os testes
        run: npx cypress run --env allure=true
        continue-on-error: true

      - name: Pega o histórico do Allure
        uses: actions/checkout@v2
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      - name: Pega os novos dados e atualiza
        uses: simple-elf/allure-report-action@master
        if: always()
        id: allure-report
        with:
          allure_results: ./allure-results
          gh_pages: gh-pages
          allure_report: allure-report
          allure_history: allure-history

      - name: Realiza deploy para o GitHub pages
        if: always()
        uses: peaceiris/actions-gh-pages@v2
        env:
          PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: allure-history

      - name: Run the action # You would run your tests before this using the output to set state/desc
        uses: Sibz/github-status-action@v1
        with: 
          authToken: ${{secrets.GITHUB_TOKEN}}
          context: 'Test run'
          description: 'Passed'
          state: 'success'
          sha: ${{github.event.pull_request.head.sha || github.sha}}
